version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sonia_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sonia_user
      POSTGRES_PASSWORD: sonia_password
      POSTGRES_DB: sonia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: